project:
  type: website

website:
  title: "Anivia documentation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - anivia_tutorial.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



