project:
  type: website

website:
  title: "Anivia documentation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorials"
        contents:
          - tutorial_deeplabcut.qmd
          - tutorial_anipose.qmd
      - section: "Guides"
        contents:
          - guide_import_export.qmd
      - section: "Reference"
        contents:
          - ref_formats.qmd

format:
  html:
    theme: cosmo
    mainfont: sans-serif
    css: styles.css
    toc: true
