project:
  type: website
  output-dir: docs

website:
  title: "Anivia documentation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorials"
        contents:
          - tutorial_deeplabcut.qmd
          - tutorial_anipose.qmd
      - section: "Guides"
        contents:
          - guide_import_export.qmd
          - guide_labeling_multiple_animals.qmd
          - guide_annotating_in_3d.qmd
      - section: "Reference"
        contents:
          - ref_formats.qmd
      - section: "Explanation"
        contents:
          - explanation_choices_anivia.qmd

format:
  html:
    theme: cosmo
    mainfont: sans-serif
    css: styles.css
    toc: true
