---
title: "Labeling with anivia: a tutorial"
author: "Lili Karashchuk"
date: "2023-01-02"
toc: true
---

Anivia is a new tool to support annotation of animal bodyparts in a web interface.
The images are loaded in your browser locally.

It is a streamlined version of [VGG VIA](https://www.robots.ox.ac.uk/~vgg/software/via/), intended specifically for animal annotation.

# Labeling in 2D
## Importing annotations

### from DeepLabCut

To import a DeepLabCut dataset, follow the steps below.
Note that you can only label one folder at a time. 

1. In the menu, click on: Import > Load DeepLabCut dataset 
2. Navigate to your DeepLabCut project
3. Go within the labeled-data
4. Select a folder and click "Upload"

If there are no labels yet, you may need to specify bodyparts (below).
Note: Due to no available libraries to parse pytables in javascript, just the h5 file with labels (not images) is sent to server to convert it to a csv to parse. 

### from Lightning Pose

To import a Lightning Pose dataset, follow the steps below.

1. In the menu, click on: Import > Load Lightning Pose dataset 
2. Navigate to your folder which contains "CollectedData.csv"
3. Select that folder and click "Upload"

## from SLEAP

To import a SLEAP dataset, follow these steps:

1. In the menu, click on: Import > Load SLEAP dataset (SLP file)
2. Select your slp file and select "Upload"

Note that SLP file must have the images padded with zeros to account for the javascript h5 loading library. 
This is already in the latest SLEAP code and will be available in future SLEAP releases.
For now, you can use [this python script](https://gist.github.com/lambdaloop/cf80b92b4a1218919c71486916eaff90) to pad your video items. 

  
## Specifying bodyparts

To add or edit the bodyparts for labeling, follow the steps below.

1. In the menu, click on: Project > Edit bodyparts
2. You will enter the Bodyparts editor, where you can add or remove bodyparts
3. You can drag bodyparts around to change the order for labeling

If you have some annotations within your files already, the bodyparts will automatically be populated.

## Labeling images

### annotating images

Place keypoints by clicking in the image. The keypoints will be placed following the order of bodyparts. (See above for how to edit the bodyparts.) 

You can move a keypoint by clicking it and dragging it.
You can delete a keypoint by selecting it and either pressing "d" or clicking the X icon in the toolbar.

To navigate across images, you can use the left/right arrow keys, clicking in the file menu, or click the left/right arrows in the toolbar.

### labeling multiple animals

Anivia supports labeling multiple animals, but only if you export to a SLEAP file currently.

The interface focuses on one animal "instance" at a time. By default when you click to place points it places them in instance 0. 

Here is how you navigate the instance interface:
- "i" for new instance (or circle plus in toolbar)
- "u" to delete an instance  (or circle minus in toolbar)
- up and down arrows to switch between instances (or circle up and down in toolbar, or just click on a point from that instance)

## Exporting annotations

### to DeepLabCut

To export your annotations to DeepLabCut, follow these steps:

1. In the menu, click on: Export > Export Annotations (DeepLabCut format)
2. Save your file as "CollectedData_SCORER.h5" within the folder within labeled-data that you imported
Replace SCORER above with the actual scorer name you specified at the top of your DeepLabCut config.yaml
 
Note: Similarly to importing, due to limitations on h5 libraries in javascript, the labels are sent to server to convert them to generate an h5 file. Again, no images are ever sent out of your machine, only labels.

### to Lightning Pose

To export your annotations to Lightning Pose, follow these steps:

1. In the menu, click on: Export > Export Annotations (Lightning Pose format)
2. Save your file as "CollectedData.csv" within the folder you imported 

### to SLEAP

To export your annotations to Lightning Pose, follow these steps:

1. In the menu, click on: Export > Export Annotations (SLP format)
2. Save your slp file wherever.

It might take a bit of time (less than a minute) to generate the SLP file for export.  



# Labeling in 3D

## format for Anipose 3D labeling data 
- It supports an ad-hoc format that should be easy to get from your anipose labeled-data. The structure is:
  - main folder with subfolders per camera
  - files in main folder
    - CollectedData.csv - file with annotations, can be generated from group of DLC files
    - calibration.toml - calibration file generated by anipose
    - config.toml - should have camera cropping offsets (if any)
  - If you upgrade anipose to latest version (1.1.2), running anipose extract-frames  will now generate this format.
  - See example zip above

## To label in 3D:
- Open anivia: https://lambdaloop.com/anivia/
- In menu: Import > "Load Anipose Dataset"
- Select the main folder (which contains all the camera subfolders)
- Click "Toggle 3D annotation" button
- You should see multiple views and points should be green/red
- Annotation proceeds same as in 2D
  - See "Help > Getting Started"
  - If you don't have any bodyparts, specify them in Project > Edit bodyparts
- When done, in menu do: Export > Export Annotations (Anipose format)
- Save the file as "CollectedData.csv" in the main Anipose folder
  - you may need to change settings in your browser to make it prompt where to save your downloaded file

## 3D annotation features
- See all the views at once!
- You can toggle to another view by clicking on it
- Points are colored by reprojection error: green is low error, red is high error.
  - It's the mean error across all views, per point. You'll have to discern which view(s) are causing the issue.
- Project points based on other views! (this feature feels magical to me)
  - Delete points you want projected (select and press "d" or click the "x" at the top)
  - Click "Project missing points"
  - Any point visible in 2+ other views will be projected onto current view
