---
title: "Tutorial: Annotate Anipose format in 3D"
toc: true
---

## An example dataset

You can find an example fly dataset from [google drive](https://drive.google.com/drive/folders/1pbGl6D-Lg7oKXwpsXamCZjpA_aMEkdEz?usp=sharing).
We will use the fly dataset in this tutorial.
This dataset is an annotation folder used for tracking flies in Karashchuk et al, "Anipose: A toolkit for robust markerless 3D pose estimation", *Cell Reports*, 2021.

::: {.callout-note icon=false collapse="true"}
### Naming scheme of fly joints in dataset

Flies have 6 legs and 4 key joints on each leg. In the annotation, we label the legs L for left, R for right, then 1-3 from front to back. For example, L2 would be the left middle leg.

The joints are named A-E corresponding to thorax-coxa joint, coxa-femur joint, femur-tibia joint, tibia-tarsus joint, and tarsus tip. Hence, L2E would be the tarsus tip on the left middle leg. 

Such condensation of keypoint name is helpful so that labels don't take up too much space in the interface.
:::

If you want another dataset for comparison, you can also find an example mouse annotation dataset [here](https://drive.google.com/drive/folders/1W-KM-W-nr-9Ys1ZN3KvAjU2TTxkaB9BM?usp=drive_link). 


## Anipose annotation format  
walk through the format

- It supports an ad-hoc format that should be easy to get from your anipose labeled-data. The structure is:
  - main folder with subfolders per camera
  - files in main folder
    - CollectedData.csv - file with annotations, can be generated from group of DLC files
    - calibration.toml - calibration file generated by anipose
    - config.toml - should have camera cropping offsets (if any)
  - If you upgrade anipose to latest version (at least 1.1.2), running anipose extract-frames  will now generate this format.


## Importing annotations

- Open anivia: https://lambdaloop.com/anivia/
- In menu: Import > "Load Anipose Dataset"
- Select the main folder (which contains all the camera subfolders)
- Click "Toggle 3D annotation" button
- You should see multiple views and points should be green/red

## Specifying bodyparts
really same as in DLC tutorial

## Labeling in 3D
- See all the views at once!
- You can toggle to another view by clicking on it
- Points are colored by reprojection error: green is low error, red is high error.
  - It's the mean error across all views, per point. You'll have to discern which view(s) are causing the issue.
- Project points based on other views! (this feature feels magical to me)
  - Delete points you want projected (select and press "d" or click the "x" at the top)
  - Click "Project missing points"
  - Any point visible in 2+ other views will be projected onto current view

## Exporting
- When done, in menu do: Export > Export Annotations (Anipose format)
- Save the file as "CollectedData.csv" in the main Anipose folder
  - you may need to change settings in your browser to make it prompt where to save your downloaded file
